### ISSUE TITLE
Add Apache license headers to all files

### ISSUE THREAD

**Issue by runseb** [NOPping/gstack#9]

**Comment by imduffy15** [comment]
Ran some bash commands, following files lack headers:

./.coveragerc
./.travis.yml
./alembic.ini
./gstack/data/server.crt
./gstack/data/server.key
./gstack/data/v1.json
./HISTORY.rst
./LICENSE.txt
./Makefile
./migrations
./migrations/alembic.ini
./migrations/env.py
./migrations/README
./migrations/script.py.mako
./migrations/versions
./migrations/versions/25c3e5241cd0_.py
./migrations/versions/76bb287a37d_.py
./pylint.rc
./pyoauth2
./pyoauth2/__init__.py
./pyoauth2/client.py
./pyoauth2/provider.py
./pyoauth2/tests
./pyoauth2/tests/__init__.py
./pyoauth2/tests/test_client.py
./pyoauth2/tests/test_integration.py
./pyoauth2/tests/test_provider.py
./pyoauth2/tests/test_utils.py
./pyoauth2/utils.py
./README.rst
./setup.py
./tests
./tests/__init__.py
./tests/data
./tests/data/authorize_security_group_ingress.json
./tests/data/create_volume_response.json
./tests/data/delete_keypair.json
./tests/data/destroy_vm_async_pending.json
./tests/data/duplicate_create_security_group.json
./tests/data/empty_describe_disk_offerings.json
./tests/data/empty_describe_images.json
./tests/data/empty_describe_instances.json
./tests/data/empty_describe_key_pairs.json
./tests/data/empty_describe_security_groups.json
./tests/data/empty_describe_volumes.json
./tests/data/empty_describe_zone.json
./tests/data/invalid_image_id.json
./tests/data/list_capabilities.json
./tests/data/list_zone_by_name_response.json
./tests/data/valid_async_deploy_vm.json
./tests/data/valid_async_destroy_vm.json
./tests/data/valid_create_keypair.json
./tests/data/valid_create_security_group.json
./tests/data/valid_delete_security_group.json
./tests/data/valid_delete_volume.json
./tests/data/valid_describe_account.json
./tests/data/valid_describe_image.json
./tests/data/valid_describe_images.json
./tests/data/valid_describe_instance.json
./tests/data/valid_describe_instances.json
./tests/data/valid_describe_key_pairs.json
./tests/data/valid_describe_regions.json
./tests/data/valid_describe_security_group.json
./tests/data/valid_describe_security_groups.json
./tests/data/valid_describe_service_offering.json
./tests/data/valid_describe_service_offerings.json
./tests/data/valid_describe_tags.json
./tests/data/valid_describe_volume.json
./tests/data/valid_describe_volumes.json
./tests/data/valid_describe_zone.json
./tests/data/valid_detach_volume.json
./tests/data/valid_get_account.json
./tests/data/valid_get_image.json
./tests/data/valid_get_instance.json
./tests/data/valid_get_instance_by_id.json
./tests/data/valid_get_security_group.json
./tests/data/valid_get_service_offering.json
./tests/data/valid_get_zone.json
./tests/data/valid_import_keypair.json
./tests/data/valid_reboot_instance.json
./tests/data/valid_register_keypair.json
./tests/data/valid_run_instance.json
./tests/data/valid_start_instance.json
./tests/data/valid_stop_instance.json
./tests/data/valid_terminate_instance.json
./tests/data/zones_search.json
./tests/discovery_tests.py
./tests/disks_tests.py
./tests/firewalls_tests.py
./tests/images_tests.py
./tests/instances_tests.py
./tests/machine_type_tests.py
./tests/networks_tests.py
./tests/operations_tests.py
./tests/project_tests.py
./tests/regions_tests.py
./tests/settings.py
./tests/utils.py
./tests/zones_tests.py

**Comment by imduffy15** [comment]
Comments aren't allowed in JSON files.... I'm assuming we can just discount them?

**Comment by runseb** [comment]
Yes I think we can.

-sebastien
